[package]
name = "painting"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.2"
egui = "0.32.2"
egui-phosphor = "0.10.0"
egui_extras = "0.32.2"
image = "0.25.8"
rand = "0.9.2"
rfd = "0.15.4"
